# Generated by Django 4.1.3 on 2023-02-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_rename_iscustomer_user_is_customer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="roomsStayed",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="seller",
            name="rating",
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name="seller",
            name="roomCount",
            field=models.IntegerField(default=0),
        ),
    ]
