# Generated by Django 4.1.3 on 2023-02-25 01:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_customer_roomsstayed_alter_seller_rating_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
