# Generated by Django 4.1.3 on 2023-02-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_remove_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default="temporary", max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
